# screen width an height
SCREEN_WIDTH, SCREEN_HEIGHT = 400, 400

# color settings
BG_COLOR = 25, 42, 86    # British PICO VOID
BORDER_COLOR = 245, 246, 250  # British LYNX WHITE
SNAKE_COLOR = 223, 249, 251
APPLE_COLOR = 126, 214, 223
SNAKE_HEAD_COLOR = 0, 0, 0
TEXT_COLOR = 255, 255, 255


# the width and height of game area
BOARD_WIDTH, BOARD_HEIGHT = 30, 30
CELL_WIDTH = 10    # assert even nunber
BORDER_WIDTH = 1

# origin snake speed
SNAKE_SPEED = 300

SNAKE_HEAD_RADIUS = 3
APPLE_RADIUS = CELL_WIDTH // 2 - 1

# anchor parameters
BOARD_LEFT = (SCREEN_WIDTH - CELL_WIDTH * BOARD_WIDTH) // 2
BOARD_TOP = (SCREEN_HEIGHT - CELL_WIDTH * BOARD_HEIGHT) // 2
BOARD_CENTER = BOARD_LEFT + CELL_WIDTH * BOARD_WIDTH // 2
BOARD_MIDDLE = BOARD_TOP + CELL_WIDTH * BOARD_HEIGHT // 2

BOARD_LEFT_TOP = (BOARD_LEFT, BOARD_TOP)
BOARD_RIGHT_TOP = (BOARD_LEFT + BOARD_WIDTH * CELL_WIDTH, BOARD_TOP)
BOARD_LEFT_BOTTOM = (BOARD_LEFT, BOARD_TOP + BOARD_HEIGHT * CELL_WIDTH)
BOARD_RIGHT_BOTTOM = (BOARD_LEFT + BOARD_WIDTH * CELL_WIDTH,
                      BOARD_TOP + BOARD_HEIGHT * CELL_WIDTH)
